name: cellular_viewer
description: "View cellular network information on your device and make your own status bar!"
publish_to: "none"
version: 0.0.3+6

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  spookyservices:
    path: /home/kipper/Documents/GitKraken/SpookyServices
    # can be found at https://github.com/SpookyKipper/SpookyServicesFlutter/
    # you can use this for local dev, but please change back to the path above when contributing
  package_info_plus: ^9.0.0
  dynamic_color: ^1.8.1
  dynamik_theme: ^0.1.5
  flutter_cell_info:
    path: /home/kipper/Documents/GitKraken/flutter_cell_info
    # can be found at https://github.com/SpookyKipper/flutter_cell_info/
    # you can use this for local dev, but please change back to the path above when contributing
  permission_handler: ^12.0.1
  clipboard: ^3.0.14
  fluttertoast: ^9.0.0
  flutter_overlay_window: ^0.5.0

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/NetworkIcons/
