name: cellular_viewer
description: "View cellular network information on your device and make your own status bar!"
publish_to: "none"
version: 0.0.1+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  spookyservices:
    path: /home/kipper/Documents/GitKraken/SpookyServices
    # can be found at https://github.com/SpookyKipper/SpookyServicesFlutter/
    # you can use this for local dev, but please change back to the path above when contributing
  package_info_plus: ^9.0.0
  dynamic_color: ^1.8.1
  dynamik_theme: ^0.1.5
  flutter_cell_info:
    path: /home/kipper/Documents/GitKraken/flutter_cell_info
    # can be found at https://github.com/SpookyKipper/flutter_cell_info/
    # you can use this for local dev, but please change back to the path above when contributing
  permission_handler: ^12.0.1
  clipboard: ^3.0.14
  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/NetworkIcons/2G.png
    - assets/images/NetworkIcons/3G.png
    - assets/images/NetworkIcons/4G.png
    - assets/images/NetworkIcons/4GPlus.png
    - assets/images/NetworkIcons/5G.png
    - assets/images/NetworkIcons/5GmmW.png
    - assets/images/NetworkIcons/5GNSA.png
    - assets/images/NetworkIcons/5GPlus.png
    - assets/images/NetworkIcons/5GPlus_With_4GPlus.png
    - assets/images/NetworkIcons/5GSA.png
    - assets/images/NetworkIcons/5GPlusSA.png
    - assets/images/NetworkIcons/5GPlusNSA.png
    - assets/images/NetworkIcons/5GSub6.png
    - assets/images/NetworkIcons/5G_With_4GPlus.png
    - assets/images/NetworkIcons/5GNSA_With_4GPlus.png
    - assets/images/NetworkIcons/5GPlusNSA_With_4GPlus.png
    - assets/images/NetworkIcons/H.png
    - assets/images/NetworkIcons/H+.png
    - assets/images/NetworkIcons/LTE.png
    - assets/images/NetworkIcons/LTE-A.png
    - assets/images/NetworkIcons/Vo5G.png
    - assets/images/NetworkIcons/VoLTE.png
    - assets/images/NetworkIcons/VoNR.png
    - assets/images/NetworkIcons/VoWiFi.png
    - assets/images/NetworkIcons/NoVoice.png
    - assets/images/NetworkIcons/CSFB.png
